export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'


export const LOGOUT_USER = 'LOGOUT_USER'

export const UPLOAD_IMAGE="UPLOAD_IMAGE"

export const HANDLE_CHANGE="HANDLE_CHANGE"

export const CLEAR_UPLOADS="CLEAR_UPLOADS"


export const CHANGE_PAGE="CHANGE_PAGE"



export const REGISTER_USER_BEGIN="REGISTER_USER_BEGIN"
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCES"
export const REGISTER_USER_ERROR="REGISTER_USER_ERROR"


export const LOGIN_USER_BEGIN="LOGIN_USER_BEGIN"
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCES"
export const LOGIN_USER_ERROR="LOGIN_USER_ERROR"

export const RESETPASSWORD_SUCCESS="RESETPASSWORD_SUCCESS"
export const RESETPASSWORD_ERROR="RESETPASSWORD_ERROR"

export const RESETPASSWORDCOMPLETE_SUCCESS="RESETPASSWORDCOMPLETE_SUCCESS"
export const RESETPASSWORDCOMPLETE_ERROR="RESETPASSWORDCOMPLETE_ERROR"



